services:
  # Backend Service
  - type: web
    plan: free
    region: frankfurt
    name: cms-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: GITHUB_REPO_OWNER
        sync: false
      - key: GITHUB_REPO_NAME
        sync: false
    healthCheckPath: /api/status

  # Frontend Service
  - type: web
    name: cms-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: cms-backend
          type: web
          property: host
      - key: VITE_GH_OWNER
        sync: false
      - key: VITE_GH_REPO
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
